name = "steveprints-at"
type = "javascript"
main = "src/index.js"
compatibility_date = "2024-12-02"

[site]
bucket = "."

[build]
command = "echo 'Static site'"

[env.production]
routes = [
  { pattern = "steveprints.at", zone_name = "steveprints.at" },
  { pattern = "www.steveprints.at", zone_name = "steveprints.at" }
]
